uploads = []
generated = []

[[outputs]]
id = "n_rcflxklUxzcVIia5Ppy"
uri = "file://.local/outputs/ISC-Mbujimayi-Soutenance-de-Jury.pptx"
type = "slides"
title = "ISC Mbujimayi — Soutenance de Jury (PPTX)"

[[outputs]]
id = "UcjEjAiNumKsxJCIoqANS"
uri = "file://.local/outputs/ISC-Mbujimayi-Soutenance-de-Jury.pdf"
type = "pdf"
title = "ISC Mbujimayi — Soutenance de Jury (PDF)"
